---
apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts/
    clusterName: kind
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: minikube
  environments:
    - key: dev
    - key: staging
    - key: production
  ingress:
    domain: 192.168.49.2.nip.io
    externalDNS: false
    namespaceSubDomain: -jx.
    ignoreLoadBalancer: true
    tls:
      email: "papyrus.zak@gmail.com"
      enabled: false
      production: false
  repository: bucketrepo
  secretStorage: local
  vault: {}
  webhook: lighthouse
